import { Inter, Poppins } from "next/font/google"
import './globals.css'
import Header from "@/sections/Header";
import Footer from "@/sections/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className} ${inter.className} antialiased`}>
      <body>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
